openapi: 3.0.0
info:
  title: SPP PAYMENT API FOR SMK-AL-IHYA
  description: OPEN API documentation for my project. !!AI generated, may not be accurate (will be updated later).
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Development server
paths:
  /ping:
    get:
      summary: Ping the server
      responses:
        '200':
          description: Server is up and running
  /api/login:
    post:
      summary: Login for both siswa and petugas
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/UserLogin'
                - $ref: '#/components/schemas/PetugasLogin'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      token:
                        type: string
        '400':
          description: Invalid request body
        '401':
          description: Unauthorized
  /api/register:
    post:
      summary: Register a new siswa
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegister'
      responses:
        '200':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid request body
  /api/users/current:
    get:
      summary: Get current user (siswa)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User data retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /api/users/current/pembayaran:
    get:
      summary: Get pembayaran for current user (siswa)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User pembayaran data retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pembayaran'
  /api/users/logout:
    delete:
      summary: Logout for current user (siswa)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Logout successful
  /api/admin/register:
    post:
      summary: Register a new petugas (admin only)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PetugasRegister'
      responses:
        '200':
          description: Petugas created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Petugas'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /api/admin/petugas:
    get:
      summary: Get all petugas (admin only)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Petugas data retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Petugas'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /api/admin/update:
    patch:
      summary: Update a petugas (admin only)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PetugasUpdate'
      responses:
        '200':
          description: Petugas updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Petugas'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /api/admin/petugas/delete/{username}:
    delete:
      summary: Delete a petugas (admin only)
      security:
        - bearerAuth: []
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Petugas deleted successfully
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /api/petugas/logout:
    delete:
      summary: Logout for petugas
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Logout successful
  /api/petugas/siswa:
    get:
      summary: Get all siswa (petugas/admin)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Siswa data retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
  /api/petugas/siswa/update:
    patch:
      summary: Update a siswa (petugas/admin)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SiswaUpdate'
      responses:
        '200':
          description: Siswa updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /api/petugas/siswa/delete/{nisn}:
    delete:
      summary: Delete a siswa (petugas/admin)
      security:
        - bearerAuth: []
      parameters:
        - name: nisn
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Siswa deleted successfully
  /api/petugas/kelas/tambah:
    post:
      summary: Add a new kelas (petugas/admin)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/KelasTambah'
      responses:
        '200':
          description: Kelas added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Kelas'
  /api/petugas/kelas:
    get:
      summary: Get all kelas (petugas/admin)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Kelas data retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Kelas'
  /api/petugas/kelas/update:
    patch:
      summary: Update a kelas (petugas/admin)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/KelasUpdate'
      responses:
        '200':
          description: Kelas updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Kelas'
  /api/petugas/kelas/delete/{id_kelas}:
    delete:
      summary: Delete a kelas (petugas/admin)
      security:
        - bearerAuth: []
      parameters:
        - name: id_kelas
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Kelas deleted successfully
  /api/petugas/spp/tambah:
    post:
      summary: Add a new spp (petugas/admin)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SppTambah'
      responses:
        '200':
          description: SPP added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Spp'
  /api/petugas/spp:
    get:
      summary: Get all spp (petugas/admin)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: SPP data retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Spp'
  /api/petugas/spp/update:
    patch:
      summary: Update a spp (petugas/admin)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SppUpdate'
      responses:
        '200':
          description: SPP updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Spp'
  /api/petugas/spp/delete/{id_spp}:
    delete:
      summary: Delete a spp (petugas/admin)
      security:
        - bearerAuth: []
      parameters:
        - name: id_spp
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: SPP deleted successfully
  /api/petugas/pembayaran/tambah:
    post:
      summary: Add a new pembayaran (petugas/admin)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PembayaranTambah'
      responses:
        '200':
          description: Pembayaran added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pembayaran'
  /api/petugas/pembayaran:
    get:
      summary: Get all pembayaran (petugas/admin)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Pembayaran data retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pembayaran'
  /api/petugas/pembayaran/delete/{id_pembayaran}:
    delete:
      summary: Delete a pembayaran (petugas/admin)
      security:
        - bearerAuth: []
      parameters:
        - name: id_pembayaran
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Pembayaran deleted successfully
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        nisn:
          type: string
        nis:
          type: string
        nama:
          type: string
        id_kelas:
          type: integer
        alamat:
          type: string
        no_telp:
          type: string
        id_spp:
          type: integer
    UserRegister:
      type: object
      properties:
        nisn:
          type: string
        nis:
          type: string
        nama:
          type: string
        id_kelas:
          type: integer
        alamat:
          type: string
        no_telp:
          type: string
        id_spp:
          type: integer
    UserLogin:
      type: object
      properties:
        nisn:
          type: string
        nama:
          type: string
    Petugas:
      type: object
      properties:
        id_petugas:
          type: integer
        username:
          type: string
        password:
          type: string
        nama_petugas:
          type: string
        level:
          type: string
          enum: [admin, petugas]
    PetugasRegister:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        nama:
          type: string
        level:
          type: string
          enum: [admin, petugas]
    PetugasLogin:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    PetugasUpdate:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        nama_petugas:
          type: string
        level:
          type: string
          enum: [admin, petugas]
    SiswaUpdate:
      type: object
      properties:
        nisn:
          type: string
        nis:
          type: string
        nama:
          type: string
        id_kelas:
          type: integer
        alamat:
          type: string
        no_telp:
          type: string
        id_spp:
          type: integer
    Kelas:
      type: object
      properties:
        id_kelas:
          type: integer
        nama_kelas:
          type: string
        kompetensi_keahlian:
          type: string
    KelasTambah:
      type: object
      properties:
        nama_kelas:
          type: string
        kompetensi_keahlian:
          type: string
    KelasUpdate:
      type: object
      properties:
        id_kelas:
          type: integer
        nama_kelas:
          type: string
        kompetensi_keahlian:
          type: string
    Spp:
      type: object
      properties:
        id_spp:
          type: integer
        tahun:
          type: integer
        nominal:
          type: integer
    SppTambah:
      type: object
      properties:
        tahun:
          type: integer
        nominal:
          type: integer
    SppUpdate:
      type: object
      properties:
        id_spp:
          type: integer
        tahun:
          type: integer
        nominal:
          type: integer
    Pembayaran:
      type: object
      properties:
        id_pembayaran:
          type: integer
        id_petugas:
          type: integer
        id_spp:
          type: integer
        nisn:
          type: string
        tgl_bayar:
          type: string
          format: date
        jumlah_bayar:
          type: integer
    PembayaranTambah:
      type: object
      properties:
        id_petugas:
          type: integer
        id_spp:
          type: integer
        nisn:
          type: string
        tgl_bayar:
          type: string
          format: date
        jumlah_bayar:
          type: integer